_target_: src.datamodules.IWSLT2017_datamodule.IWSLT2017DataModule
data_dir: ${paths.data_dir}
batch_size: 128
num_workers: 0
pin_memory: False
language_pair: ["en", "de"]
spm_model_path: "https://download.pytorch.org/models/text/xlmr.sentencepiece.bpe.model"
vocab_path: "https://download.pytorch.org/models/text/xlmr.vocab.pt"
